/home/chenqh23/ser1de/protobuf/protoc Message0.proto --cpp_out=.
echo "Message0.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message1.proto --cpp_out=.
echo "Message1.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message2.proto --cpp_out=.
echo "Message2.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message3.proto --cpp_out=.
echo "Message3.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message4.proto --cpp_out=.
echo "Message4.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message5.proto --cpp_out=.
echo "Message5.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message6.proto --cpp_out=.
echo "Message6.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message7.proto --cpp_out=.
echo "Message7.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message8.proto --cpp_out=.
echo "Message8.proto done"
/home/chenqh23/ser1de/protobuf/protoc Message9.proto --cpp_out=.
echo "Message9.proto done"
